# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: twBLE2MQTT-darwin
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}}

  - id: twBLE2MQTT-others
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    ignore:
      - goos: windows
        goarch: arm
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}}

archives:
  - formats: [ 'tar.gz' ]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

nfpms:
  - ids:
      - twBLE2MQTT-others
    homepage: https://github.com/twsnmp/twBLE2MQTT
    maintainer: Masayuki Yamai <twsnmp@gmail.com>
    description: Bluetooth BLE to MQTT bridge for TWSNMP FC
    license: Apache 2.0
    formats:
      - deb
      - rpm
    bindir: /usr/sbin
    epoch: 1
